---
name: "Dactyl keyboard"

on:
  push:
    branches:
      - master
      - actions

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    name: "Build artifacts"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: satackey/action-docker-layer-caching@v0.0.11
        continue-on-error: true
      - name: Clean up
        run: rm -r things/*
      - name: Build
        run: make build
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          draft: false
          files: things/*
          tag_name: v${{ github.run_number }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}